---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: push docker image
  image: plugins/docker
  settings:
    tags: latest
    squash: true
    pull_image: true
    compress: true
    no_cache: true
    experimental: true
    dockerfile: Dockerfile
    context: .
    repo: nonchris/telegram-update-bot
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
  when:
    branch:
    - main
    event:
    - push